# Notebook to crossmatch an external catalog with the ALeRCE database

```Author: Francisco Förster, modifications: Kay Medina, Alejandra Muñoz Arancibia. Last updated: 20261005```

*It is highly recommended that you try this notebook in Google Colab using the following [link](https://colab.research.google.com/github/alercebroker/usecases/blob/master/notebooks/ZTF/ALeRCE_ExternalCatalog_Xmatch.ipynb).*
This will avoid you from having to sort out library installation problems and focus on the contents of the tutorial. You can try installing the dependencies later in your own system.

In [1]:
import pandas as pd
from astropy.table import Table

In [2]:
#!pip install pyvo
import pyvo

### TAP connection setup

Instead of using a direct PostgreSQL connection, we connect to the ALeRCE ZTF legacy database using Astronomical Data Query Language ([ADQL](https://www.ivoa.net/documents/ADQL/)) queries to the ALeRCE TAP service, returning results as pandas dataframes. Database table names are prefixed with `ztf.` (e.g. `ztf.object`, `ztf.detection`, etc.).

In [3]:
TAP_URL = "https://tap.alerce.online/tap"
tap_service = pyvo.dal.TAPService(TAP_URL)

def tap_query_list(query, table, maxrec=10_000_000):
    result = tap_service.search(query, uploads={'mylist': table},
                                maxrec=maxrec)
    return result.to_table().to_pandas()

## Example external catalog

In [4]:
# The catalog should have id_source, ra, and dec columns
df = pd.read_csv("https://github.com/alercebroker/usecases/blob/master/example_data/watchlist.csv?raw=True")
df.head()

  id_source          ra        dec
0  source_1  254.843418   1.646404
1  source_2  215.416280  13.229551

### Crossmatch via ADQL cone search

A previous version of this notebook used a PostgreSQL-specific `q3c_join` plus a `WITH ... (VALUES ...)` common table expression (CTE) to crossmatch the input catalog against the database in a single query. Neither is part of ADQL, so on TAP we run an ADQL cone search (`CONTAINS`/`CIRCLE`) with a `TAP_UPLOAD` spatial join (the external catalog is uploaded as an astropy table).

In [5]:
def ztf_crossmatch(df, search_radius=1):
    '''
    df: external catalog dataframe (with columns id_source, ra, dec)
    search_radius: crossmatch radius in arcsec (default=1)

    The output is a dataframe with the source id, ra, and dec, as well as the
    ALeRCE database oid, meanra, meandec, the crossmatch distance in arcsec
    (dist_arcsec) and the time of first detection (firstmjd).
    '''
    # CIRCLE wants the radius in degrees; the catalog convention here is arcsec.
    radius_deg = search_radius / 3600

    objs = Table.from_pandas(df)
    
    query = '''
    SELECT
        c.id_source, c.ra, c.dec,
        o.oid, o.meanra, o.meandec, o.firstmjd,
        3600 * DISTANCE(POINT('ICRS', c.ra, c.dec),
                        POINT('ICRS', o.meanra, o.meandec)) AS dist_arcsec
    FROM
        tap_upload.mylist AS c
    JOIN ztf.object AS o
    ON
        CONTAINS(POINT('ICRS', o.meanra, o.meandec),
                 CIRCLE('ICRS', c.ra, c.dec, %g)) = 1
    ''' % radius_deg
    #print(query)
    
    df_objs = tap_query_list(query, objs)
    
    return df_objs

## Do the crossmatch

In [6]:
results = ztf_crossmatch(df)
results

,id_source,ra,dec,oid,meanra,meandec,firstmjd,dist_arcsec
0,source_1,254.843418,1.646404,ZTF26aauxhbe,254.843416,1.646405,61167.339722,0.008017
1,source_2,215.416280,13.229551,ZTF26aasmsqg,215.416280,13.229552,61145.361192,0.002212